services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password}
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  stremio-saga-addon:
    build: .
    ports:
      - "8080:7000"
    environment:
      PORT: 7000
      RATE_LIMIT_ENABLED: true
      LOG_ENABLED: true
      LOG_LEVEL: info
      NODE_ENV: production
      LOG_INTERVAL_DELETION: 3d
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
    depends_on:
      redis:
        condition: service_healthy
